name: C++ CUDA Test

on:
  push:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t lowlevelrl .

    - name: Run tests in Docker container 
      run: |
        set -e
        docker run lowlevelrl
